In [1]:
import pandas as pd

# 1. Create a tiny dataset
data = {
    'Material': ['Iron', 'Alumina', 'Polyethylene'],
    'Class': ['Metal', 'Ceramic', 'Polymer'],
    'Melting_Temp_K': [1811, 2345, 400]
}

df = pd.DataFrame(data)

# 2. Unit Conversion: Kelvin to Celsius
# Formula: C = K - 273.15
df['Melting_Temp_C'] = df['Melting_Temp_K'] - 273.15

print("--- After Unit Conversion ---")
display(df)

# 3. Filter the data (Ceramics only)
ceramics_only = df[df['Class'] == 'Ceramic']

print("\n--- Filtered Data (Ceramics Only) ---")
display(ceramics_only)

# 4. Categorical Encoding (One-Hot Encoding)
# Convert the 'Class' column into binary columns
df_encoded = pd.get_dummies(df, columns=['Class'])

print("\n--- After Categorical Encoding ---")
display(df_encoded)

# 5. Filter the encoded data (Ceramics only)
ceramics_encoded = df_encoded[df_encoded['Class_Ceramic'] == True]
# Alternatively:
# ceramics_encoded = df_encoded[df_encoded['Class_Ceramic'] == 1]

print("\n--- Filtered Encoded Data (Ceramics Only) ---")
display(ceramics_encoded)

--- After Unit Conversion ---

       Material    Class  Melting_Temp_K  Melting_Temp_C
0          Iron    Metal            1811         1537.85
1       Alumina  Ceramic            2345         2071.85
2  Polyethylene  Polymer             400          126.85

--- Filtered Data (Ceramics Only) ---

  Material    Class  Melting_Temp_K  Melting_Temp_C
1  Alumina  Ceramic            2345         2071.85

--- After Categorical Encoding ---

,Material,Melting_Temp_K,Melting_Temp_C,Class_Ceramic,Class_Metal,Class_Polymer
0,Iron,1811,1537.85,False,True,False
1,Alumina,2345,2071.85,True,False,False
2,Polyethylene,400,126.85,False,False,True

--- Filtered Encoded Data (Ceramics Only) ---

,Material,Melting_Temp_K,Melting_Temp_C,Class_Ceramic,Class_Metal,Class_Polymer
1,Alumina,2345,2071.85,True,False,False