In [1]:
import pandas as pd

# 1. Create a tiny dataset
data = {
    'Material': ['Iron', 'Alumina', 'Polyethylene'],
    'Class': ['Metal', 'Ceramic', 'Polymer'],
    'Melting_Temp_K': [1811, 2345, 400]
}
df = pd.DataFrame(data)

# 2. Unit Conversion: Kelvin to Celsius
# Formula: C = K - 273.15
df['Melting_Temp_C'] = df['Melting_Temp_K'] - 273.15
print("— After Unit Conversion —")
display(df)

# 3. Categorical Encoding (One-Hot Encoding)
# We turn the 'Class' text column into machine-readable binary columns
df_encoded = pd.get_dummies(df, columns=['Class'])
print("\n— After Categorical Encoding —")
display(df_encoded)

— After Unit Conversion —

       Material    Class  Melting_Temp_K  Melting_Temp_C
0          Iron    Metal            1811         1537.85
1       Alumina  Ceramic            2345         2071.85
2  Polyethylene  Polymer             400          126.85

— After Categorical Encoding —

,Material,Melting_Temp_K,Melting_Temp_C,Class_Ceramic,Class_Metal,Class_Polymer
0,Iron,1811,1537.85,False,True,False
1,Alumina,2345,2071.85,True,False,False
2,Polyethylene,400,126.85,False,False,True

In [3]:
# Filter rows where Melting_Temp_K is greater than 1000
filtered_df = df[df['Melting_Temp_K'] > 1000]

# Display the filtered data
display(filtered_df)

NameError: name 'df' is not defined

In [4]:
import pandas as pd

data = {
    "Name": ["Iron", "Copper", "Aluminum"],
    "Density": [7.87, 8.96, 2.70]
}

df = pd.DataFrame(data)

print(df)

       Name  Density
0      Iron     7.87
1    Copper     8.96
2  Aluminum     2.70

In [5]:
import pandas as pd

data = {
    "Name": ["Iron", "Copper", "Aluminum"],
    "Density": [7.87, 8.96, 2.70]
}

df = pd.DataFrame(data)

print(df)

       Name  Density
0      Iron     7.87
1    Copper     8.96
2  Aluminum     2.70

In [6]:
# Filter rows where Melting_Temp_K is greater than 1000
filtered_df = df[df['Melting_Temp_K'] > 1000]

# Display the filtered data
display(filtered_df)

KeyError: 'Melting_Temp_K'

In [7]:
import pandas as pd

data = {
    "Name": ["Iron", "Copper", "Aluminum"],
    "Density": [7.87, 8.96, 2.70]
}

df = pd.DataFrame(data)

print(df)

       Name  Density
0      Iron     7.87
1    Copper     8.96
2  Aluminum     2.70

In [8]:
# Filter rows where Melting_Temp_K is greater than 1000
filtered_df = df[df['Melting_Temp_K'] > 1000]

# Display the filtered data
display(filtered_df)

KeyError: 'Melting_Temp_K'

In [9]:
Filtered_df = df[df['Melting Temp (K)'] > 1000]

KeyError: 'Melting Temp (K)'